#!/bin/bash

BASENAME=clusterware
NAME=stack

alces_modules_version=3.2.9

# ensure all children die when we do
trap "/bin/kill -- -$BASHPID &>/dev/null" EXIT INT TERM

function toggle_spin () {
	if [ -z "$spin_pid" ]; then
	    (
		i=1
		sp="/-\|"
		printf " "
		while true;
		do
		    printf "\b[1m${sp:i++%${#sp}:1}[0m"
		    if [[ i -eq ${#sp} ]]; then
			i=0
		    fi
		    sleep 0.2
		done
	    ) &
	    sleep 1
	    spin_pid=$!
	else
	    sleep 1
	    kill $spin_pid
	    wait $spin_pid 2>/dev/null
	    printf "\b"
	    unset spin_pid
	fi
}

function title() {
    printf "\n > $1\n"
}

function doing() {
    if [ -z "$2" ]; then
	pad=12
    else
	pad=$2
    fi
    printf "    [36m%${pad}s[0m ... " "$1"
    toggle_spin
}

function say_done () {
    toggle_spin
    if [ $1 -gt 0 ]; then
	echo '[31mFAIL[0m'
	exit 1
    else
	echo '[32mOK[0m '
    fi
}

title "Creating initial directory structure"
doing 'Create'
[[ -d "${alces_PATH}/opt/${BASENAME}/lib/${NAME}" ]] || mkdir -p "${alces_PATH}/opt/${BASENAME}/lib/${NAME}"

# Make directories
LOGDIR="var/log/${NAME}"
for a in var/lib/${NAME}/repos/base var/lib/${NAME} $LOGDIR; do
    [[ -d "${alces_PATH}/${a}" ]] || mkdir -p "${alces_PATH}/${a}"
done

say_done $?

# Create initial configuration files
title "Creating initial configuration"
doing "Create"
cp -r "${alces_SRC_PATH}/${NAME}/dist/plugins.d"/* "${alces_PATH}/etc/${BASENAME}/plugins.d"
if (( UID == 0 )); then
    cp -r "${alces_SRC_PATH}/${NAME}/etc/global"/* "${alces_PATH}/etc"
    cp -r "${alces_SRC_PATH}/${NAME}/etc/system"/* "${alces_PATH}/etc"
else
    cp -r "${alces_SRC_PATH}/${NAME}/etc/global"/* "${alces_PATH}/etc"
    cp -r "${alces_SRC_PATH}/${NAME}/etc/user"/* "${alces_PATH}/etc"
fi
chmod 600 "${alces_PATH}/etc/ipmi.conf"
chmod 600 "${alces_PATH}/etc/ifcfg-bmc"
say_done $?

title "Installing '${NAME}' facility"
doing 'Install'
cp -r "${alces_SRC_PATH}/${NAME}/lib" "${alces_PATH}/opt/${BASENAME}/lib/${NAME}"
say_done $?
doing 'Link'
for a in "${alces_PATH}/opt/${BASENAME}/lib/${NAME}/lib/actions"/*; do
  ln -sf $a "${alces_PATH}/opt/${BASENAME}/lib/actions"
done
say_done $?

# install ruby lib gems
title "Configuring ruby components"
cd "${alces_PATH}/opt/${BASENAME}/lib/${NAME}/lib/ruby"
doing 'Configure'
"${alces_RUBYHOME}/bin/bundle" install --local &> "${alces_PATH}/${LOGDIR}/components-install${alces_OS}.log"
say_done $?

title "Installing pdsh"
cd "${alces_SRC_PATH}"
doing 'Extract'
cp "${alces_SRC_PATH}/${NAME}/archives"/* "${alces_ARCHIVES_PATH}"
tar jxf "${alces_ARCHIVES_PATH}/pdsh-2.29.tar.bz2"
say_done $?
cd pdsh-2.29
doing 'Configure'
./configure --prefix="${alces_PATH}/opt/${alces_OS}/pdsh/2.29" --with-ssh --with-rcmd-rank-list=ssh,rsh,exec --with-genders &> "${alces_PATH}/${LOGDIR}/pdsh-configure-${alces_OS}.log"
say_done $?
doing 'Compile'
make &> "${alces_PATH}/${LOGDIR}/pdsh-make-${alces_OS}.log"
say_done $?
doing 'Install'
make install &> "${alces_PATH}/${LOGDIR}/pdsh-install-${alces_OS}/.log"
say_done $?
